project:
  type: website

website:
  title: "ManyPhons"
  navbar:
    left:
      - href: index.qmd
        text: ICPhS Special Session

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



