---
title: "Changing research culture - Toward big team speech science"
---


## Special Session at ICPhS in Prague (9th August)


We invite you to join us in a very special special session at this year's ICPhS in Prague. 
The last decade has been an interesting time for the experimental sciences: Experimental disciplines realized that many published findings cannot be replicated[^1], published analyses cannot be reproduced[^2], and many conclusions do not generalize across cultures, languages and even alternative analyses[^3]. 
Many of these issues are related to a research culture which treats individual Principal Investigators as unconnected islands of research and development. 
With these limited resources, it is difficult to replicate our work, stress-test our analyses and generalize our findings. 
But what if we told you that this is not what it needs to be?

What could be is a globally distributed network of phonetic laboratories that coordinates data collection for democratically selected studies. 
This approach is often referred to as the Big Team Science approach and has already been successfully implemented across different disciplines[^4][^5][^6]. 
These collaborative efforts provide rich empirical contributions that are characterized by rigor, transparency and generalizability. 

In this special session, we will discuss opportunities, challenges, and limitations of such an approach. 
And the session will be special indeed: Because it is about getting things done. 
Together. 
Instead of watching yet another set of short talks, we will form groups and discuss Big Team Science in phonetics. 
And we have a concrete goal in mind: We will write a white paper together which discusses the potential and limitations of Big Team Science in phonetics. 
So we will be taken notes in a shared online document which will be distilled and drafted into a manuscript after the special issue. 

Do you want to be actively contributing to a new era in how speech sciences are done? 
Do you want to be co-author on our paper? 
Come and join us in Prague.

## Details

- **Who?** Everybody is welcome. No background knowledge necessary. 
- **When?** 9th of August, 13:10-14:40 (but check the ICPhS schedule [here](https://www.icphs2023.org/programme/programme-/))
- **Where?** South Hall 2B


## Tentative schedule

- 13:10: A short introduction to Big Team Science and the Special Session (by Timo Roettger)
- 13:25-14:10: Group discussions on challenges of the BTS approach to Phonetics
- 14:10-14:30: General discussion and summary 
- 14:30: Wrap up (by Timo Roettger)


If you have any questions or are unsure whether this is for you, please reach out to either [Joseph Casillas](mailto:joseph.casillas@rutges.edu) or [Timo Roettger](mailto:timo.roettger@iln.uio.no). 


[^1]: https://www.science.org/doi/10.1126/science.aac4716
[^2]: https://royalsocietypublishing.org/doi/10.1098/rsos.180448
[^3]: https://journals.sagepub.com/doi/full/10.1177/25152459231162567
[^4]: https://manybabies.org
[^5]: https://psysciacc.org
[^6]: http://themanybirds.com